server:
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apptest
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /
